### ISSUE TITLE
Put everything from src/ under the src/os3 folder

### ISSUE THREAD

**Issue by rhornig** [inet-framework/os3#2]
It would be great to reorganize the code a bit and place the whole project under the src/os3 folder (see how INET is organized). The reason is that this project would probably be used along with other projects and without a toplevel directory it is hard to tell that from which project a given header file is pulled.

**Comment by doughodson** [comment]
I am absolutely going to do that soon.  I was a very happy camper to see 
that organization in inet 2.99 as it was something I was going to 
suggest.  I honestly didn't notice as I pulled inet master from github 
-- I only noticed when I downloaded 2.99 zip file off website.

inet is an important project from many standpoints -- not only does it 
provide a lot of capability, but I also see it as a 'model' of how omnet 
code should be structured and organized when building packages intended 
to be used by others, or as you say, provide a 'base' for other 
developments.

Doug

**Comment by doughodson** [comment]
This is done now -- at the moment I'm still using inet 2.5 -- will 
transition to 2.99 shortly.

Code has changed a lot, satellites are 'flying' but I need to check 
other basic functionality to see if code is really working correctly.

Doug
